exports.HIDE_APPLICATION = 'APPLICATION:HIDE';
exports.CHART_MESSAGE = 'CHART:MESSAGE';
exports.CHART_MESSAGE_HISTORY = 'CHART:MESSAGE:HISTORY';
exports.DASHBOARD_STATUS = 'DASHBOARD:STATUS';
exports.DASHBOARD_SETTING = 'DASHBOARD:SETTING';
exports.UPDATE_DASHBOARD_PORT = 'UPDATE:DASHBOARD:PORT';
exports.LIVE_START = 'LIVE:START';

